import {
  House,
  Wallet,
  UserCheck,
  Package,
  CalendarCheck,
  LifeBuoy,
  Hammer,
  Megaphone,
  Calendar,
  Folder,
  ListChecks,
  Vote,
  Landmark,
  BookUser,
  Store,
  Siren,
  Sparkles,
  Shield,
  Receipt,
  Users,
  Building2,
  Scale,
  Mail,
  UsersRound,
  Wrench,
  Boxes,
  Briefcase,
  PiggyBank,
  IdCard,
  ChartColumn,
  FileText,
  Settings,
  History,
  List,
  Clock,
  Menu,
  Circle,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: House,
  house: House,
  wallet: Wallet,
  "user-check": UserCheck,
  package: Package,
  "calendar-check": CalendarCheck,
  "life-buoy": LifeBuoy,
  hammer: Hammer,
  megaphone: Megaphone,
  calendar: Calendar,
  folder: Folder,
  "list-checks": ListChecks,
  vote: Vote,
  landmark: Landmark,
  "book-user": BookUser,
  store: Store,
  siren: Siren,
  sparkles: Sparkles,
  shield: Shield,
  receipt: Receipt,
  users: Users,
  building: Building2,
  scale: Scale,
  mail: Mail,
  "users-round": UsersRound,
  wrench: Wrench,
  boxes: Boxes,
  briefcase: Briefcase,
  "piggy-bank": PiggyBank,
  "id-card": IdCard,
  chart: ChartColumn,
  "file-text": FileText,
  settings: Settings,
  history: History,
  list: List,
  clock: Clock,
  menu: Menu,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Circle;
  return <Icon className={className} aria-hidden="true" />;
}
