/** Etiquetas en español natural para valores de enums (con tildes). */
const OVERRIDES: Record<string, string> = {
  // Gobierno (encuestas, votaciones, asambleas)
  UNICA: "Opción única",
  MULTIPLE: "Opción múltiple",
  ESCALA: "Escala de 1 a 5",
  UNANIME: "Unánime",
  PODER: "Por poder",
  DANO_ZONA_COMUN: "Daño en zona común",
  DANO_UNIDAD: "Daño en unidad",
  PETICION: "Petición",
  EN_REVISION: "En revisión",
  EN_ESPERA_RESIDENTE: "Esperando al residente",
  REABIERTO: "Reabierto",
  EN_PORTERIA: "En portería",
  PROPIETARIO_OCUPA: "Propietario ocupa",
  AIRBNB_O_SIMILAR: "Renta corta (Airbnb)",
  EN_VENTA: "En venta",
  EN_ACUERDO: "En acuerdo de pago",
  GENERACION_MENSUAL: "Generación mensual",
  INTERES_MORA: "Interés de mora",
  ALQUILER_ZONA: "Alquiler de zona",
  ADMINISTRACION: "Administración",
  EXTRAORDINARIA: "Extraordinaria",
  PSE: "PSE",
  NEQUI: "Nequi",
  BANCOLOMBIA_QR: "Bancolombia QR",
  CONSIGNACION: "Consignación",
  TRANSFERENCIA: "Transferencia",
  NO_SHOW: "No se presentó",
  SALA_JUNTAS: "Sala de juntas",
  BBQ: "BBQ",
  CALIFICADA_70: "Calificada (70 %)",
  PROPIETARIOS_AL_DIA: "Propietarios al día",
  LLAMADA_RESIDENTE: "Llamada al residente",
  LISTA_FRECUENTES: "Lista de frecuentes",
  QR: "Código QR",
  CODIGO: "Código",
  EMPLEADO_DOMESTICO: "Empleado doméstico",
  VISITANTE_FRECUENTE: "Visitante frecuente",
  AUTORIZADO_RECOGER_PAQUETES: "Autorizado para paquetes",
  AUTORIZADO_MENORES: "Autorizado para recoger menores",
  PENDIENTE_APROBACION: "Pendiente de aprobación",
  EN_DESCARGOS: "En descargos",
  EN_MEDIACION: "En mediación",
  EN_CURSO: "En curso",
  EN_PROCESO: "En proceso",
  EN_MANTENIMIENTO: "En mantenimiento",
  FUERA_SERVICIO: "Fuera de servicio",
  DADO_DE_BAJA: "Dado de baja",
  POR_VENCER: "Por vencer",
  PENDIENTE_MODERACION: "Pendiente de moderación",
  PERDIDO_ENCONTRADO: "Perdido / encontrado",
  EMERGENCIA_GENERAL: "Emergencia general",
  MEDICA: "Médica",
  PANICO: "Pánico",
  CONJUNTO_CASAS: "Conjunto de casas",
  DEPOSITO: "Depósito",
  CAMARA_COMERCIO: "Cámara de comercio",
  SEGURIDAD_SOCIAL: "Seguridad social",
  CERTIFICACION: "Certificación",
  PENDIENTE: "Pendiente",
  NOTA_CREDITO: "Nota crédito",
  DECISION_TELEFONICA: "Decisión telefónica",
  COMPLETADA: "Completada",
  PAGADA: "Pagada",
  ANULADA: "Anulada",
  PARCIAL: "Parcial",
  // Comunicaciones, documentos y calendario (fase 8)
  REGLAMENTO: "Reglamento de PH",
  MANUAL_CONVIVENCIA: "Manual de convivencia",
  ESTADO_FINANCIERO: "Estados financieros",
  FUMIGACION: "Fumigación",
  CORTE_SERVICIO: "Corte de servicio",
  CUIDADO_MASCOTAS: "Cuidado de mascotas",
  TUTORIAS: "Tutorías",
  ENVIANDO: "Enviando",
  // Cartera (Fase 3)
  WHATSAPP: "WhatsApp",
  SMS: "SMS",
  POR_COEFICIENTE: "Por coeficiente",
  IGUAL_POR_UNIDAD: "Igual por unidad",
  INTERES: "Intereses",
  APERTURA: "Saldo de apertura",
  EMPAREJADA: "Emparejada",
  CREADA: "Pago creado",
  IGNORADA: "Ignorada",
  CUMPLIDO: "Cumplido",
  INCUMPLIDO: "Incumplido",
  // Portería
  DANO: "Daño",
  DOMICILIARIO: "Domiciliario",
  ANULACION: "Anulación",
  CRITICA: "Crítica",
  TECNICO: "Técnico",
  // Reservas y facturación electrónica (fase 5)
  SIMULADO: "Simulado",
  SALON: "Salón",
  FACTUS: "Factus",
  ALANUBE: "Alanube",
  SIN_FACTURA: "Sin factura",
  NO_APLICA: "No aplica",
  EVENTO: "Evento del conjunto",
  SOLO_FINES_SEMANA: "Solo fines de semana y festivos",
  UN_TURNO_POR_DIA: "Un turno por día",
  DIAS_PERMITIDOS: "Días permitidos",
  MAX_ASISTENTES: "Máximo de asistentes",
  // pagos en línea
  SIMULADOR: "Simulador",
  MERCADOPAGO: "Mercado Pago",
  WOMPI: "Wompi",
  COBRO_ADMINISTRACION: "Cobro de administración",
  // Residentes: tipos de documento y alertas
  CC: "Cédula de ciudadanía",
  CE: "Cédula de extranjería",
  TI: "Tarjeta de identidad",
  RC: "Registro civil",
  PA: "Pasaporte",
  PEP: "Permiso especial de permanencia",
  PPT: "Permiso por protección temporal",
  NIT: "NIT",
  FALSA_ALARMA: "Falsa alarma",
  CONTRA_INCENDIO: "Contra incendios",
  // Mantenimiento, proveedores y presupuesto
  RUT: "RUT",
  POLIZA: "Póliza",
  PROGRAMADO: "Programado",
  ACTIVO_QR: "QR del activo",
  SOBREEJECUTADO: "Sobreejecutado",
  // PQRS, convivencia, obras y mudanzas (fase 7)
  FELICITACION: "Felicitación",
  ESCALADO_MULTA: "Escalado a multa",
  LEIDO: "Leído",
  REMODELACION: "Remodelación",
  PUBLICO: "Página pública",
  APP: "App",
  A_TIEMPO: "A tiempo",
};

export function label(v: string | null | undefined): string {
  if (!v) return "—";
  if (OVERRIDES[v]) return OVERRIDES[v];
  const s = v.replace(/_/g, " ").toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function options<T extends string>(values: readonly T[] | Record<string, T>) {
  const arr = Array.isArray(values) ? values : Object.values(values);
  return (arr as T[]).map((v) => ({ value: v, label: label(v) }));
}

type Tone = "default" | "secondary" | "destructive" | "outline" | "success" | "warning" | "info";

const TONES: Record<string, Tone> = {
  CERRADA: "secondary",
  // positivos
  PAGADA: "success",
  APROBADO: "success",
  APROBADA: "success",
  ACTIVO: "success",
  ACTIVA: "success",
  VIGENTE: "success",
  ENTREGADO: "success",
  RESUELTO: "success",
  CERRADO: "secondary",
  CUMPLIDA: "success",
  COMPLETADA: "success",
  VALIDADA: "success",
  OPERATIVO: "success",
  ATENDIDA: "success",
  AUTORIZADA: "success",
  FINALIZADA: "secondary",
  PUBLICADA: "success",
  ENVIADA: "success",
  ENVIADO: "success",
  AL_DIA: "success",
  // intermedios
  PENDIENTE: "warning",
  PARCIAL: "warning",
  CUMPLIDO: "success",
  INCUMPLIDO: "destructive",
  EMPAREJADA: "success",
  CREADA: "success",
  IGNORADA: "secondary",
  SOLICITADA: "warning",
  EN_PORTERIA: "warning",
  ABIERTO: "info",
  ABIERTA: "info",
  EN_REVISION: "info",
  ASIGNADO: "info",
  EN_PROCESO: "info",
  EN_CURSO: "info",
  EN_ESPERA_RESIDENTE: "warning",
  PROGRAMADA: "info",
  CONVOCADA: "info",
  NOTIFICADA: "warning",
  EN_DESCARGOS: "warning",
  PROPUESTA: "secondary",
  EN_ACUERDO: "info",
  POR_VENCER: "warning",
  EN_MANTENIMIENTO: "warning",
  PENDIENTE_APROBACION: "warning",
  PENDIENTE_MODERACION: "warning",
  BORRADOR: "secondary",
  // negativos
  RECHAZADO: "destructive",
  RECHAZADA: "destructive",
  ANULADO: "destructive",
  ANULADA: "destructive",
  CANCELADA: "destructive",
  VENCIDO: "destructive",
  VENCIDA: "destructive",
  ERROR: "destructive",
  REABIERTO: "destructive",
  RATIFICADA: "destructive",
  FUERA_SERVICIO: "destructive",
  NO_SHOW: "destructive",
  MORA: "destructive",
  CRITICA: "destructive",
  ALTA: "warning",
  URGENTE: "destructive",
  EXPIRADA: "destructive",
  REVOCADA: "secondary",
  DEVUELTO: "secondary",
  INACTIVO: "secondary",
  BLOQUEADO: "destructive",
  // Portería
  USADA: "secondary",
  INGRESO: "success",
  SALIDA: "info",
  ANULACION: "destructive",
  DISPONIBLE: "success",
  PRESTADO: "warning",
  OCUPADO: "warning",
  PERDIDO: "destructive",
  MEDIA: "info",
  ENVIANDO: "info",
  FALSA_ALARMA: "secondary",
  // Mantenimiento, proveedores y presupuesto
  PAGADO: "success",
  TERMINADO: "secondary",
  PROGRAMADO: "info",
  PREVENTIVO: "info",
  CORRECTIVO: "warning",
  LEGAL: "default",
  DADO_DE_BAJA: "secondary",
  SOBREEJECUTADO: "destructive",
  // PQRS, convivencia, obras y mudanzas (fase 7)
  LEIDO: "info",
  RESPONDIDO: "info",
  ESCALADO_MULTA: "warning",
  EN_MEDIACION: "info",
  ACUERDO: "success",
  ESCALADO: "destructive",
  GRAVE: "destructive",
  MODERADA: "warning",
  LEVE: "secondary",
  BAJA: "secondary",
  A_TIEMPO: "success",
};

export function tone(v: string | null | undefined): Tone {
  return (v && TONES[v]) || "outline";
}
