/** Etiquetas en español natural para valores de enums (con tildes). */
const OVERRIDES: Record<string, string> = {
  DANO_ZONA_COMUN: "Daño en zona común",
  DANO_UNIDAD: "Daño en unidad",
  PETICION: "Petición",
  EN_REVISION: "En revisión",
  EN_ESPERA_RESIDENTE: "Esperando al residente",
  REABIERTO: "Reabierto",
  EN_PORTERIA: "En portería",
  PROPIETARIO_OCUPA: "Propietario ocupa",
  AIRBNB_O_SIMILAR: "Renta corta (Airbnb)",
  EN_VENTA: "En venta",
  EN_ACUERDO: "En acuerdo de pago",
  GENERACION_MENSUAL: "Generación mensual",
  INTERES_MORA: "Interés de mora",
  ALQUILER_ZONA: "Alquiler de zona",
  ADMINISTRACION: "Administración",
  EXTRAORDINARIA: "Extraordinaria",
  PSE: "PSE",
  NEQUI: "Nequi",
  BANCOLOMBIA_QR: "Bancolombia QR",
  CONSIGNACION: "Consignación",
  TRANSFERENCIA: "Transferencia",
  NO_SHOW: "No se presentó",
  SALA_JUNTAS: "Sala de juntas",
  BBQ: "BBQ",
  CALIFICADA_70: "Calificada (70 %)",
  PROPIETARIOS_AL_DIA: "Propietarios al día",
  LLAMADA_RESIDENTE: "Llamada al residente",
  LISTA_FRECUENTES: "Lista de frecuentes",
  QR: "Código QR",
  CODIGO: "Código",
  EMPLEADO_DOMESTICO: "Empleado doméstico",
  VISITANTE_FRECUENTE: "Visitante frecuente",
  AUTORIZADO_RECOGER_PAQUETES: "Autorizado para paquetes",
  AUTORIZADO_MENORES: "Autorizado para recoger menores",
  PENDIENTE_APROBACION: "Pendiente de aprobación",
  EN_DESCARGOS: "En descargos",
  EN_MEDIACION: "En mediación",
  EN_CURSO: "En curso",
  EN_PROCESO: "En proceso",
  EN_MANTENIMIENTO: "En mantenimiento",
  FUERA_SERVICIO: "Fuera de servicio",
  DADO_DE_BAJA: "Dado de baja",
  POR_VENCER: "Por vencer",
  PENDIENTE_MODERACION: "Pendiente de moderación",
  PERDIDO_ENCONTRADO: "Perdido / encontrado",
  EMERGENCIA_GENERAL: "Emergencia general",
  MEDICA: "Médica",
  PANICO: "Pánico",
  CONJUNTO_CASAS: "Conjunto de casas",
  DEPOSITO: "Depósito",
  CAMARA_COMERCIO: "Cámara de comercio",
  SEGURIDAD_SOCIAL: "Seguridad social",
  CERTIFICACION: "Certificación",
  PENDIENTE: "Pendiente",
  NOTA_CREDITO: "Nota crédito",
  DECISION_TELEFONICA: "Decisión telefónica",
  COMPLETADA: "Completada",
  PAGADA: "Pagada",
  ANULADA: "Anulada",
  PARCIAL: "Parcial",
};

export function label(v: string | null | undefined): string {
  if (!v) return "—";
  if (OVERRIDES[v]) return OVERRIDES[v];
  const s = v.replace(/_/g, " ").toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function options<T extends string>(values: readonly T[] | Record<string, T>) {
  const arr = Array.isArray(values) ? values : Object.values(values);
  return (arr as T[]).map((v) => ({ value: v, label: label(v) }));
}

type Tone = "default" | "secondary" | "destructive" | "outline" | "success" | "warning" | "info";

const TONES: Record<string, Tone> = {
  // positivos
  PAGADA: "success",
  APROBADO: "success",
  APROBADA: "success",
  ACTIVO: "success",
  ACTIVA: "success",
  VIGENTE: "success",
  ENTREGADO: "success",
  RESUELTO: "success",
  CERRADO: "secondary",
  CUMPLIDA: "success",
  COMPLETADA: "success",
  VALIDADA: "success",
  OPERATIVO: "success",
  ATENDIDA: "success",
  AUTORIZADA: "success",
  FINALIZADA: "secondary",
  PUBLICADA: "success",
  ENVIADA: "success",
  ENVIADO: "success",
  AL_DIA: "success",
  // intermedios
  PENDIENTE: "warning",
  PARCIAL: "warning",
  SOLICITADA: "warning",
  EN_PORTERIA: "warning",
  ABIERTO: "info",
  ABIERTA: "info",
  EN_REVISION: "info",
  ASIGNADO: "info",
  EN_PROCESO: "info",
  EN_CURSO: "info",
  EN_ESPERA_RESIDENTE: "warning",
  PROGRAMADA: "info",
  CONVOCADA: "info",
  NOTIFICADA: "warning",
  EN_DESCARGOS: "warning",
  PROPUESTA: "secondary",
  EN_ACUERDO: "info",
  POR_VENCER: "warning",
  EN_MANTENIMIENTO: "warning",
  PENDIENTE_APROBACION: "warning",
  PENDIENTE_MODERACION: "warning",
  BORRADOR: "secondary",
  // negativos
  RECHAZADO: "destructive",
  RECHAZADA: "destructive",
  ANULADO: "destructive",
  ANULADA: "destructive",
  CANCELADA: "destructive",
  VENCIDO: "destructive",
  VENCIDA: "destructive",
  ERROR: "destructive",
  REABIERTO: "destructive",
  RATIFICADA: "destructive",
  FUERA_SERVICIO: "destructive",
  NO_SHOW: "destructive",
  MORA: "destructive",
  CRITICA: "destructive",
  ALTA: "warning",
  URGENTE: "destructive",
  EXPIRADA: "destructive",
  REVOCADA: "secondary",
  DEVUELTO: "secondary",
  INACTIVO: "secondary",
  BLOQUEADO: "destructive",
};

export function tone(v: string | null | undefined): Tone {
  return (v && TONES[v]) || "outline";
}
